import { db } from "../src/db";
import { entries } from "../src/db/schema";

await db
  .insert(entries)
  .values([
    {
      lemma: "ambulō",
      lemmaPlain: "ambulo",
      partOfSpeech: "verb",
      principalParts: "ambulō, ambulāre, ambulāvī, ambulātum",
      conjugation: "1",
      meaningEn: "to walk",
    },
    {
      lemma: "amō",
      lemmaPlain: "amo",
      partOfSpeech: "verb",
      principalParts: "amō, amāre, amāvī, amātum",
      conjugation: "1",
      meaningEn: "to love",
    },
    {
      lemma: "audiō",
      lemmaPlain: "audio",
      partOfSpeech: "verb",
      principalParts: "audiō, audīre, audīvī, audītum",
      conjugation: "4",
      meaningEn: "to hear, listen to",
    },
    {
      lemma: "cantō",
      lemmaPlain: "canto",
      partOfSpeech: "verb",
      principalParts: "cantō, cantāre, cantāvī, cantātum",
      conjugation: "1",
      meaningEn: "to sing",
    },
    {
      lemma: "currō",
      lemmaPlain: "curro",
      partOfSpeech: "verb",
      principalParts: "currō, currere, cucurrī, cursum",
      conjugation: "3",
      meaningEn: "to run",
    },
    {
      lemma: "labōrō",
      lemmaPlain: "laboro",
      partOfSpeech: "verb",
      principalParts: "labōrō, labōrāre, labōrāvī, labōrātum",
      conjugation: "1",
      meaningEn: "to work",
    },
    {
      lemma: "rīdeō",
      lemmaPlain: "rideo",
      partOfSpeech: "verb",
      principalParts: "rīdeō, rīdēre, rīsī, rīsum",
      conjugation: "2",
      meaningEn: "to laugh, smile",
    },
    {
      lemma: "sedeō",
      lemmaPlain: "sedeo",
      partOfSpeech: "verb",
      principalParts: "sedeō, sedēre, sēdī, sessum",
      conjugation: "2",
      meaningEn: "to sit",
    },
    {
      lemma: "spectō",
      lemmaPlain: "specto",
      partOfSpeech: "verb",
      principalParts: "spectō, spectāre, spectāvī, spectātum",
      conjugation: "1",
      meaningEn: "to watch, look at",
    },
    {
      lemma: "videō",
      lemmaPlain: "video",
      partOfSpeech: "verb",
      principalParts: "videō, vidēre, vīdī, vīsum",
      conjugation: "2",
      meaningEn: "to see",
    },
    {
      lemma: "vocō",
      lemmaPlain: "voco",
      partOfSpeech: "verb",
      principalParts: "vocō, vocāre, vocāvī, vocātum",
      conjugation: "1",
      meaningEn: "to call",
    },
    {
      lemma: "fīlia",
      lemmaPlain: "filia",
      partOfSpeech: "noun",
      principalParts: "fīliae",
      gender: "f",
      declension: "1",
      meaningEn: "daughter",
    },
    {
      lemma: "fīlius",
      lemmaPlain: "filius",
      partOfSpeech: "noun",
      principalParts: "fīliī",
      gender: "m",
      declension: "2",
      meaningEn: "son",
    },
    {
      lemma: "hortus",
      lemmaPlain: "hortus",
      partOfSpeech: "noun",
      principalParts: "hortī",
      gender: "m",
      declension: "2",
      meaningEn: "garden",
    },
    {
      lemma: "māter",
      lemmaPlain: "mater",
      partOfSpeech: "noun",
      principalParts: "mātris",
      gender: "f",
      declension: "3",
      meaningEn: "mother",
    },
    {
      lemma: "pater",
      lemmaPlain: "pater",
      partOfSpeech: "noun",
      principalParts: "patris",
      gender: "m",
      declension: "3",
      meaningEn: "father",
    },
    {
      lemma: "puella",
      lemmaPlain: "puella",
      partOfSpeech: "noun",
      principalParts: "puellae",
      gender: "f",
      declension: "1",
      meaningEn: "girl",
    },
    {
      lemma: "rosa",
      lemmaPlain: "rosa",
      partOfSpeech: "noun",
      principalParts: "rosae",
      gender: "f",
      declension: "1",
      meaningEn: "rose",
    },
    {
      lemma: "servus",
      lemmaPlain: "servus",
      partOfSpeech: "noun",
      principalParts: "servī",
      gender: "m",
      declension: "2",
      meaningEn: "slave",
    },
    {
      lemma: "et",
      lemmaPlain: "et",
      partOfSpeech: "conjunction",
      meaningEn: "and",
    },
    {
      lemma: "nōn",
      lemmaPlain: "non",
      partOfSpeech: "adverb",
      meaningEn: "not",
    },
    {
      lemma: "quoque",
      lemmaPlain: "quoque",
      partOfSpeech: "adverb",
      meaningEn: "also",
    },
    {
      lemma: "sed",
      lemmaPlain: "sed",
      partOfSpeech: "conjunction",
      meaningEn: "but",
    },
    {
      lemma: "tum",
      lemmaPlain: "tum",
      partOfSpeech: "adverb",
      meaningEn: "then",
    },
  ])
  .onConflictDoNothing({ target: [entries.lemma] });
