import { db } from "../src/db";
import { entries } from "../src/db/schema";

await db
  .insert(entries)
  .values([
    {
      lemma: "ambulō",
      lemmaPlain: "ambulo",
      partOfSpeech: "verb",
      principalParts: "ambulō, ambulāre, ambulāvī, ambulātum",
      conjugation: "1",
      meaningEn: "to walk",
    },
    {
      lemma: "amō",
      lemmaPlain: "amo",
      partOfSpeech: "verb",
      principalParts: "amō, amāre, amāvī, amātum",
      conjugation: "1",
      meaningEn: "to love",
    },
    {
      lemma: "audiō",
      lemmaPlain: "audio",
      partOfSpeech: "verb",
      principalParts: "audiō, audīre, audīvī, audītum",
      conjugation: "4",
      meaningEn: "to hear, listen to",
    },
    {
      lemma: "cantō",
      lemmaPlain: "canto",
      partOfSpeech: "verb",
      principalParts: "cantō, cantāre, cantāvī, cantātum",
      conjugation: "1",
      meaningEn: "to sing",
    },
    {
      lemma: "currō",
      lemmaPlain: "curro",
      partOfSpeech: "verb",
      principalParts: "currō, currere, cucurrī, cursum",
      conjugation: "3",
      meaningEn: "to run",
    },
    {
      lemma: "labōrō",
      lemmaPlain: "laboro",
      partOfSpeech: "verb",
      principalParts: "labōrō, labōrāre, labōrāvī, labōrātum",
      conjugation: "1",
      meaningEn: "to work",
    },
    {
      lemma: "rīdeō",
      lemmaPlain: "rideo",
      partOfSpeech: "verb",
      principalParts: "rīdeō, rīdēre, rīsī, rīsum",
      conjugation: "2",
      meaningEn: "to laugh, smile",
    },
    {
      lemma: "sedeō",
      lemmaPlain: "sedeo",
      partOfSpeech: "verb",
      principalParts: "sedeō, sedēre, sēdī, sessum",
      conjugation: "2",
      meaningEn: "to sit",
    },
    {
      lemma: "spectō",
      lemmaPlain: "specto",
      partOfSpeech: "verb",
      principalParts: "spectō, spectāre, spectāvī, spectātum",
      conjugation: "1",
      meaningEn: "to watch, look at",
    },
    {
      lemma: "videō",
      lemmaPlain: "video",
      partOfSpeech: "verb",
      principalParts: "videō, vidēre, vīdī, vīsum",
      conjugation: "2",
      meaningEn: "to see",
    },
    {
      lemma: "vocō",
      lemmaPlain: "voco",
      partOfSpeech: "verb",
      principalParts: "vocō, vocāre, vocāvī, vocātum",
      conjugation: "1",
      meaningEn: "to call",
    },
    {
      lemma: "fīlia",
      lemmaPlain: "filia",
      partOfSpeech: "noun",
      principalParts: "fīliae",
      gender: "f",
      declension: "1",
      meaningEn: "daughter",
    },
    {
      lemma: "fīlius",
      lemmaPlain: "filius",
      partOfSpeech: "noun",
      principalParts: "fīliī",
      gender: "m",
      declension: "2",
      meaningEn: "son",
    },
    {
      lemma: "hortus",
      lemmaPlain: "hortus",
      partOfSpeech: "noun",
      principalParts: "hortī",
      gender: "m",
      declension: "2",
      meaningEn: "garden",
    },
    {
      lemma: "māter",
      lemmaPlain: "mater",
      partOfSpeech: "noun",
      principalParts: "mātris",
      gender: "f",
      declension: "3",
      meaningEn: "mother",
    },
    {
      lemma: "pater",
      lemmaPlain: "pater",
      partOfSpeech: "noun",
      principalParts: "patris",
      gender: "m",
      declension: "3",
      meaningEn: "father",
    },
    {
      lemma: "puella",
      lemmaPlain: "puella",
      partOfSpeech: "noun",
      principalParts: "puellae",
      gender: "f",
      declension: "1",
      meaningEn: "girl",
    },
    {
      lemma: "rosa",
      lemmaPlain: "rosa",
      partOfSpeech: "noun",
      principalParts: "rosae",
      gender: "f",
      declension: "1",
      meaningEn: "rose",
    },
    {
      lemma: "servus",
      lemmaPlain: "servus",
      partOfSpeech: "noun",
      principalParts: "servī",
      gender: "m",
      declension: "2",
      meaningEn: "slave",
    },
    {
      lemma: "et",
      lemmaPlain: "et",
      partOfSpeech: "conjunction",
      meaningEn: "and",
    },
    {
      lemma: "nōn",
      lemmaPlain: "non",
      partOfSpeech: "adverb",
      meaningEn: "not",
    },
    {
      lemma: "quoque",
      lemmaPlain: "quoque",
      partOfSpeech: "adverb",
      meaningEn: "also",
    },
    {
      lemma: "sed",
      lemmaPlain: "sed",
      partOfSpeech: "conjunction",
      meaningEn: "but",
    },
    {
      lemma: "tum",
      lemmaPlain: "tum",
      partOfSpeech: "adverb",
      meaningEn: "then",
    },
    {
      lemma: "oppidum",
      lemmaPlain: "oppidum",
      partOfSpeech: "noun",
      principalParts: "oppidī",
      gender: "n",
      declension: "2",
      meaningEn: "town",
    },
    {
      lemma: "fluvius",
      lemmaPlain: "fluvius",
      partOfSpeech: "noun",
      principalParts: " fluviī",
      gender: "m",
      declension: "2",
      meaningEn: "river",
    },
    {
      lemma: "īnsula",
      lemmaPlain: "insula",
      partOfSpeech: "noun",
      principalParts: "īnsulae",
      gender: "f",
      declension: "1",
      meaningEn: "island",
    },
    {
      lemma: "imperium",
      lemmaPlain: "imperium",
      partOfSpeech: "noun",
      principalParts: "imperiī",
      gender: "n",
      declension: "2",
      meaningEn: "empire",
    },
    {
      lemma: "vīlla",
      lemmaPlain: "villa",
      partOfSpeech: "noun",
      principalParts: "vīllae",
      gender: "f",
      declension: "1",
      meaningEn: "villa, country house",
    },
    {
      lemma: "via",
      lemmaPlain: "via",
      partOfSpeech: "noun",
      principalParts: "viae",
      gender: "f",
      declension: "1",
      meaningEn: "road, street, path",
    },
    {
      lemma: "aqua",
      lemmaPlain: "aqua",
      partOfSpeech: "noun",
      principalParts: "aquae",
      gender: "f",
      declension: "1",
      meaningEn: "water",
    },
    {
      lemma: "cēna",
      lemmaPlain: "cena",
      partOfSpeech: "noun",
      principalParts: "cēnae",
      gender: "f",
      declension: "1",
      meaningEn: "dinner, supper",
    },
    {
      lemma: "equus",
      lemmaPlain: "equus",
      partOfSpeech: "noun",
      principalParts: "equī",
      gender: "m",
      declension: "2",
      meaningEn: "horse",
    },
    {
      lemma: "amīcus",
      lemmaPlain: "amicus",
      partOfSpeech: "noun",
      principalParts: "amīcī",
      gender: "m",
      declension: "2",
      meaningEn: "male friend",
    },
    {
      lemma: "portō",
      lemmaPlain: "porto",
      partOfSpeech: "verb",
      principalParts: "portō, portāre, portāvī, portātum",
      conjugation: "1",
      meaningEn: "to carry",
    },
    {
      lemma: "parō",
      lemmaPlain: "paro",
      partOfSpeech: "verb",
      principalParts: "parō, parāre, parāvī, parātum",
      conjugation: "1",
      meaningEn: "to prepare",
    },
    {
      lemma: "habitō",
      lemmaPlain: "habito",
      partOfSpeech: "verb",
      principalParts: "habitō, habitāre, habitāvī, habitātum",
      conjugation: "1",
      meaningEn: "to live in",
    },
  ])
  .onConflictDoNothing({ target: [entries.lemma] });
