import { normalizeLemma } from "#/utils/search/rules";
import { db } from "../src/db";
import { entries } from "../src/db/schema";

const words = [{
  lemma: "ambulō",
  partOfSpeech: "verb",
  principalParts: "ambulō, ambulāre, ambulāvī, ambulātum",
  conjugation: "1",
  meaningEn: "to walk",
},
{
  lemma: "amō",
  partOfSpeech: "verb",
  principalParts: "amō, amāre, amāvī, amātum",
  conjugation: "1",
  meaningEn: "to love",
},
{
  lemma: "audiō",
  partOfSpeech: "verb",
  principalParts: "audiō, audīre, audīvī, audītum",
  conjugation: "4",
  meaningEn: "to hear, listen to",
},
{
  lemma: "cantō",
  partOfSpeech: "verb",
  principalParts: "cantō, cantāre, cantāvī, cantātum",
  conjugation: "1",
  meaningEn: "to sing",
},
{
  lemma: "currō",
  partOfSpeech: "verb",
  principalParts: "currō, currere, cucurrī, cursum",
  conjugation: "3",
  meaningEn: "to run",
},
{
  lemma: "labōrō",
  partOfSpeech: "verb",
  principalParts: "labōrō, labōrāre, labōrāvī, labōrātum",
  conjugation: "1",
  meaningEn: "to work",
},
{
  lemma: "rīdeō",
  partOfSpeech: "verb",
  principalParts: "rīdeō, rīdēre, rīsī, rīsum",
  conjugation: "2",
  meaningEn: "to laugh, smile",
},
{
  lemma: "sedeō",
  partOfSpeech: "verb",
  principalParts: "sedeō, sedēre, sēdī, sessum",
  conjugation: "2",
  meaningEn: "to sit",
},
{
  lemma: "spectō",
  partOfSpeech: "verb",
  principalParts: "spectō, spectāre, spectāvī, spectātum",
  conjugation: "1",
  meaningEn: "to watch, look at",
},
{
  lemma: "videō",
  partOfSpeech: "verb",
  principalParts: "videō, vidēre, vīdī, vīsum",
  conjugation: "2",
  meaningEn: "to see",
},
{
  lemma: "vocō",
  partOfSpeech: "verb",
  principalParts: "vocō, vocāre, vocāvī, vocātum",
  conjugation: "1",
  meaningEn: "to call",
},
{
  lemma: "fīlia",
  partOfSpeech: "noun",
  principalParts: "fīliae",
  gender: "f",
  declension: "1",
  meaningEn: "daughter",
},
{
  lemma: "fīlius",
  partOfSpeech: "noun",
  principalParts: "fīliī",
  gender: "m",
  declension: "2",
  meaningEn: "son",
},
{
  lemma: "hortus",
  partOfSpeech: "noun",
  principalParts: "hortī",
  gender: "m",
  declension: "2",
  meaningEn: "garden",
},
{
  lemma: "māter",
  partOfSpeech: "noun",
  principalParts: "mātris",
  gender: "f",
  declension: "3",
  meaningEn: "mother",
},
{
  lemma: "pater",
  partOfSpeech: "noun",
  principalParts: "patris",
  gender: "m",
  declension: "3",
  meaningEn: "father",
},
{
  lemma: "puella",
  partOfSpeech: "noun",
  principalParts: "puellae",
  gender: "f",
  declension: "1",
  meaningEn: "girl",
},
{
  lemma: "rosa",
  partOfSpeech: "noun",
  principalParts: "rosae",
  gender: "f",
  declension: "1",
  meaningEn: "rose",
},
{
  lemma: "servus",
  partOfSpeech: "noun",
  principalParts: "servī",
  gender: "m",
  declension: "2",
  meaningEn: "slave",
},
{
  lemma: "et",
  partOfSpeech: "conjunction",
  meaningEn: "and",
},
{
  lemma: "nōn",
  partOfSpeech: "adverb",
  meaningEn: "not",
},
{
  lemma: "quoque",
  partOfSpeech: "adverb",
  meaningEn: "also",
},
{
  lemma: "sed",
  partOfSpeech: "conjunction",
  meaningEn: "but",
},
{
  lemma: "tum",
  partOfSpeech: "adverb",
  meaningEn: "then",
},
{
  lemma: "oppidum",
  partOfSpeech: "noun",
  principalParts: "oppidī",
  gender: "n",
  declension: "2",
  meaningEn: "town",
},
{
  lemma: "fluvius",
  partOfSpeech: "noun",
  principalParts: "fluviī",
  gender: "m",
  declension: "2",
  meaningEn: "river",
},
{
  lemma: "īnsula",
  partOfSpeech: "noun",
  principalParts: "īnsulae",
  gender: "f",
  declension: "1",
  meaningEn: "island",
},
{
  lemma: "imperium",
  partOfSpeech: "noun",
  principalParts: "imperiī",
  gender: "n",
  declension: "2",
  meaningEn: "empire",
},
{
  lemma: "vīlla",
  partOfSpeech: "noun",
  principalParts: "vīllae",
  gender: "f",
  declension: "1",
  meaningEn: "villa, country house",
},
{
  lemma: "via",
  partOfSpeech: "noun",
  principalParts: "viae",
  gender: "f",
  declension: "1",
  meaningEn: "road, street, path",
},
{
  lemma: "aqua",
  partOfSpeech: "noun",
  principalParts: "aquae",
  gender: "f",
  declension: "1",
  meaningEn: "water",
},
{
  lemma: "cēna",
  partOfSpeech: "noun",
  principalParts: "cēnae",
  gender: "f",
  declension: "1",
  meaningEn: "dinner, supper",
},
{
  lemma: "equus",
  partOfSpeech: "noun",
  principalParts: "equī",
  gender: "m",
  declension: "2",
  meaningEn: "horse",
},
{
  lemma: "amīcus",
  partOfSpeech: "noun",
  principalParts: "amīcī",
  gender: "m",
  declension: "2",
  meaningEn: "male friend",
},
{
  lemma: "portō",
  partOfSpeech: "verb",
  principalParts: "portō, portāre, portāvī, portātum",
  conjugation: "1",
  meaningEn: "to carry",
},
{
  lemma: "parō",
  partOfSpeech: "verb",
  principalParts: "parō, parāre, parāvī, parātum",
  conjugation: "1",
  meaningEn: "to prepare",
},
{
  lemma: "habitō",
  partOfSpeech: "verb",
  principalParts: "habitō, habitāre, habitāvī, habitātum",
  conjugation: "1",
  meaningEn: "to live in",
},
{
  lemma: "abacus",
  partOfSpeech: "noun",
  principalParts: "abacī",
  gender: "m",
  declension: "2",
  meaningEn: "abacus, counting board, square board",
},
{
  lemma: "littera",
  partOfSpeech: "noun",
  principalParts: "litterae",
  gender: "f",
  declension: "1",
  meaningEn: "letter (of the alphabet), letter, literature",
},
{
  lemma: "numerus",
  partOfSpeech: "noun",
  principalParts: "numerī",
  gender: "m",
  declension: "2",
  meaningEn: "number",
},
{
  lemma: "verbum",
  partOfSpeech: "noun",
  principalParts: "verbi",
  gender: "n",
  declension: "2",
  meaningEn: "word, verb (grammar)",
},
{
  lemma: "calculus",
  partOfSpeech: "noun",
  principalParts: "calculī",
  gender: "m",
  declension: "2",
  meaningEn: "pebble, stone, calculation",
},
{
  lemma: "ostendō",
  partOfSpeech: "verb",
  principalParts: "ostendō, ostendere, ostendī, ostentum",
  conjugation: "3",
  meaningEn: "to expose, exhibit, show",
},
{
  lemma: "fēlīciter",
  partOfSpeech: "adverb",
  meaningEn: "happily, favorably, fortunately",
},
{
  lemma: "fax",
  partOfSpeech: "noun",
  principalParts: "facis",
  gender: "f",
  declension: "3",
  meaningEn: "torch",
},
{
  lemma: "spērō",
  partOfSpeech: "verb",
  principalParts: "spērō, spērāre, spērāvī, spērātum",
  conjugation: "1",
  meaningEn: "to hope, expect, anticipate, assume",
},
{
  lemma: "dubitō",
  partOfSpeech: "verb",
  principalParts: "dubitō, dubitāre, dubitāvī, dubitātum",
  conjugation: "1",
  meaningEn: "to waver (in opinion), be uncertain, doubt, hesitate, ponder",
},
{
  lemma: "rogō",
  partOfSpeech: "verb",
  principalParts: "rogō, rogāre, rogāvī, rogātum",
  conjugation: "1",
  meaningEn: "to ask, enquire, request, beg",
},
{
  lemma: "superō",
  partOfSpeech: "verb",
  principalParts: "superō, superāre, superāvī, superātum",
  conjugation: "1",
  meaningEn: "to surmount, rise above, surpass, exceed, be superior, overcome",
}, {
  lemma: "tēlum",
  partOfSpeech: "noun",
  principalParts: "tēlī",
  gender: "n",
  declension: "2",
  meaningEn: "a spear, projectile weapon (javelin, arrow, etc.)",
},
{
  lemma: "auxilium",
  partOfSpeech: "noun",
  principalParts: "auxiliī",
  gender: "n",
  declension: "2",
  meaningEn: "help, aid, assistance, relief, antidote, remedy",
},
{
  lemma: "mūrus",
  partOfSpeech: "noun",
  principalParts: "mūrī",
  gender: "m",
  declension: "2",
  meaningEn: "wall, city wall(s)",
},
{
  lemma: "fabula",
  partOfSpeech: "noun",
  principalParts: "fabulae",
  gender: "f",
  declension: "1",
  meaningEn: "story, tale, discourse, narrative",
}]

await db
  .insert(entries)
  .values(words.map((w) => ({ ...w, lemmaPlain: normalizeLemma(w.lemma) })))
  .onConflictDoNothing({ target: [entries.lemma] });