/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerbumLemmaRouteImport } from './routes/verbum.$lemma'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerbumLemmaRoute = VerbumLemmaRouteImport.update({
  id: '/verbum/$lemma',
  path: '/verbum/$lemma',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/verbum/$lemma': typeof VerbumLemmaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/verbum/$lemma': typeof VerbumLemmaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/verbum/$lemma': typeof VerbumLemmaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/verbum/$lemma'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/verbum/$lemma'
  id: '__root__' | '/' | '/verbum/$lemma'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VerbumLemmaRoute: typeof VerbumLemmaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verbum/$lemma': {
      id: '/verbum/$lemma'
      path: '/verbum/$lemma'
      fullPath: '/verbum/$lemma'
      preLoaderRoute: typeof VerbumLemmaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VerbumLemmaRoute: VerbumLemmaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
